### PR TITLE
Adding profile support

### PR DESCRIPTION
**Pull request by Beanow**
Fixes https://github.com/emilsvennesson/kodi-viaplay/issues/34

Making a draft PR to get your feedback on this so far. It adds "Select profile" and "Log out" to the settings.
(As well as the user_id and profile_id, while it's in development, final would hide those.)

image

It will automatically ask to choose a profile when opening the root page, if you haven't already.
Kind of like the "Who's watching?" dialog on the official apps.

An easy way to verify your profile is correctly selected, is to see if `viaplay:starred` or `viaplay:watched` has the correct items.

@Mariusz89B @heppen-dev @zuzia-dev
What's your opinion on using the settings menu like this, instead of adding it to the root page?

### CODE REVIEW

**Comment by heppen-dev** [comment]
Yeah, I'm fine with it.
It's much better approach than listing it on root page. 
About that window. I assume it's a custom dialog, right?
If so, we can make it look kind of better, even trying to match the current window from official app.

**Comment by Beanow** [comment]
> I assume it's a custom dialog, right? If so, we can make it look kind of better, even trying to match the current window from official app.
> 
> #edit Oh, I see. It's not a custom dialog. My bad :)

It's a https://romanvm.github.io/Kodistubs/_autosummary/xbmcgui.html#xbmcgui.Dialog.select
https://github.com/Mariusz89B/kodi-viaplay/blob/d3a51dbd4aaf19d10a23475e9fe48a0192080a02/resources/lib/kodihelper.py#L92

Maybe [`xbmcgui.ListItem.setArt`](https://romanvm.github.io/Kodistubs/_autosummary/xbmcgui.html#xbmcgui.ListItem.setArt) would allow the avatars to display here? :shrug:

**Comment by Beanow** [comment]
Looks like we *could* use the icons, if we use `useDetail=True` for the dialog.
That means we get list items about 3 lines high, a second label option, and icon support.

image

**Comment by heppen-dev** [comment]
> Looks like we _could_ use the icons, if we use `useDetail=True` for the dialog. That means we get list items about 3 lines high, a second label option, and icon support.
> 
> image

Ok, I see. This looks good. The second line could be last login if possible. 
I just checked and we have "updated" key in persistentLogin endpoint. Maybe it will be better than ID in my opinion.

**Comment by Beanow** [comment]
@heppen-dev yeah I just tried out the `type: adult|child` field, and that looks useful. The `updated` field though is when the profile itself was last updated. Mine shows March 18th for example, while I used that profile multiple times this weekend.

Ones that look interesting to me are:
```json
{
  "isOwner": true,
  "type": "adult",
  "restricted": false,
  "language": "nl",
}
```

**Comment by heppen-dev** [comment]
> @heppen-dev yeah I just tried out the `type: adult|child` field, and that looks useful. The `updated` field though is when the profile itself was last updated. Mine shows March 18th for example, while I used that profile multiple times this weekend.
> 
> Ones that look interesting to me are:
> 
> ```json
> {
>   "isOwner": true,
>   "type": "adult",
>   "restricted": false,
>   "language": "nl",
> }
> ```

Basically this 3 infos are usefull:
- isOwner
- type
- lang
We can combine it somehow. 

Just say when you are ready and we can merge :)

**Comment by Beanow** [comment]
@heppen-dev like so?

image

@Mariusz89B Yeah I spotted the preselect, I've got that already implemented as, the current profile or none preselected.
(That's the green highlight)

**Comment by Beanow** [comment]
Pushed that change, though none of it is translated yet.
https://github.com/Mariusz89B/kodi-viaplay/blob/53d82a9a703a1497b8984ea128b839c58f6624d3/resources/language/resource.language.sv_se/strings.po#L276-L298

**Comment by heppen-dev** [comment]
It seems, profile does not works well with different Viaplay versions. We need more test before merge.

**Comment by Beanow** [comment]
@heppen-dev do you mean on other countries' sites? Which ones are you trying and what does it do? Silently ignore profiles or errors?

**Comment by Mariusz89B** [comment]
> @heppen-dev do you mean on other countries' sites? Which ones are you trying and what does it do? Silently ignore profiles or errors?

A solution would be to set a single user as an exception if there is missing information in the json dictionary.

**Comment by heppen-dev** [comment]
Hey @Beanow we have added profiles support to our repository with @zuzia-dev
Since I was based kind of on your solution, added you to providers and changelog. Hope you are fine with it.
Also, I solved the issue with different sites versions. Profiles should works everywhere.
You can find our version of Viaplay in https://heppen-dev.github.io repository.

**Comment by Beanow** [comment]
@heppen-dev your version seems to work with NL as well.
What did the issue end up being for other sites?

Closing this, as your fixes seem preferable.

**Comment by heppen-dev** [comment]
There was a KeyError related to language key in response. It's not exist in some sites.

**Pull request closed without merging**
